"""Init_Migration

Revision ID: e776b9f796f9
Revises: 
Create Date: 2026-03-28 17:23:00.628455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e776b9f796f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arcs_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_arcs_content'))
    )
    op.create_index(op.f('ix_arcs_content_id'), 'arcs_content', ['id'], unique=False)
    op.create_table('chapters_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapters_content'))
    )
    op.create_index(op.f('ix_chapters_content_id'), 'chapters_content', ['id'], unique=False)
    op.create_table('entities_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('CHARACTER', 'LOCATION', name='entitytype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities_content'))
    )
    op.create_index(op.f('ix_entities_content_canonical_name'), 'entities_content', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_entities_content_id'), 'entities_content', ['id'], unique=False)
    op.create_index(op.f('ix_entities_content_type'), 'entities_content', ['type'], unique=False)
    op.create_table('frames_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detailed_prompt', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('use_detailed_prompt', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_frames_content'))
    )
    op.create_index(op.f('ix_frames_content_id'), 'frames_content', ['id'], unique=False)
    op.create_table('scenes_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenes_content'))
    )
    op.create_index(op.f('ix_scenes_content_id'), 'scenes_content', ['id'], unique=False)
    op.create_table('stories_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stories_content'))
    )
    op.create_index(op.f('ix_stories_content_id'), 'stories_content', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stories_content_id'), table_name='stories_content')
    op.drop_table('stories_content')
    op.drop_index(op.f('ix_scenes_content_id'), table_name='scenes_content')
    op.drop_table('scenes_content')
    op.drop_index(op.f('ix_frames_content_id'), table_name='frames_content')
    op.drop_table('frames_content')
    op.drop_index(op.f('ix_entities_content_type'), table_name='entities_content')
    op.drop_index(op.f('ix_entities_content_id'), table_name='entities_content')
    op.drop_index(op.f('ix_entities_content_canonical_name'), table_name='entities_content')
    op.drop_table('entities_content')
    op.drop_index(op.f('ix_chapters_content_id'), table_name='chapters_content')
    op.drop_table('chapters_content')
    op.drop_index(op.f('ix_arcs_content_id'), table_name='arcs_content')
    op.drop_table('arcs_content')
    # ### end Alembic commands ###
